Add short-circuit check to form-decode-str and pre-lookup charset
ring-clojure/ring-codec pull request #38
Opened 2023-01-17 20:36 UTC by bsless

Closes #37

2023-01-17 21:13 UTC, bsless commented
@borkdude you might care to check if this is sci/babashka compatible or direct me on how to check it myself

2023-01-17 21:15 UTC, borkdude commented on src/ring/util/codec.clj
> +        (.contains encoded "+")
You might just want to use `str/includes?` here

2023-01-17 21:16 UTC, borkdude commented
I don't see any problems but I left one comment which will make it more performant in bb :)

2023-01-17 21:21 UTC, bsless commented on src/ring/util/codec.clj
> +        (.contains encoded "+")
Why is it more performant in bb? I see it calls the same class method in the end

2023-01-17 21:24 UTC, borkdude commented on src/ring/util/codec.clj
> +        (.contains encoded "+")
Because interop is dynamic and relies on reflection in bb whereas `str/includes?` is a pre-compiled function

2023-01-19 08:44 UTC, bsless commented
Narrowed the changes down only to the short circuit check

@borkdude can't use `include?` as it was added in 1.8 and ring codec supports 1.7

2023-01-20 01:21 UTC, weavejester requested changes
Thanks for the PR. I have a few suggestions.

2023-01-20 01:21 UTC, weavejester commented on src/ring/util/codec.clj
> +
I don't think this is directly related to the feature, so these lines should be removed from the PR.

2023-01-20 01:21 UTC, weavejester commented on src/ring/util/codec.clj
> +  (or (.contains s "+") (.contains s "%")))
No need to put the argument list on a different line, and I think we can give it a more descriptive name. Something like `form-encoded-chars?`. Also, didn't @borkdude suggest using `clojure.string/includes?` instead of `.contains`?

2023-01-20 01:21 UTC, weavejester commented on src/ring/util/codec.clj
> +         (URLDecoder/decode encoded encoding))
Is this `let` there because Clojure isn't quite smart enough to get the right type hint otherwise?

2023-01-21 20:36 UTC, bsless commented
@weavejester Suggested changes done besides:
- `str/includes?`: requires clojure 1.8
- let binding the encoding: compiler couldn't figure out the type hint, but the next MR with charset changes fixes that

2023-01-26 17:27 UTC, weavejester commented
Thanks! Could you change the commit message to:

```
Add short-circuit check to form-decode-str

Fixes #37.
```

It's a small change, but just helps indicate that the commit closes #37, rather than being tangentially related. Otherwise it all looks good to merge!

2023-01-26 19:55 UTC, bsless commented
Done :)

2023-01-27 00:59 UTC, merged