Replace default charset string type to Charset
ring-clojure/ring-codec pull request #41
Opened 2023-01-27 08:06 UTC by bsless

By providing the default encoding as Charset and not String we can avoid repeated lookups in hot paths.

Closes #40

2023-01-27 13:26 UTC, weavejester requested changes
Thanks for the PR. I have some suggestions, but overall good. If `percent-decode` now supports charsets, I think we need to add a few basic tests.

2023-01-27 13:26 UTC, weavejester commented on src/ring/util/codec.clj
> +(def ^Charset utf-8 (Charset/forName "UTF-8"))
Var should be marked as private if not part of the public API.

2023-01-27 13:26 UTC, weavejester commented on src/ring/util/codec.clj
> +  (if (nil? s) utf-8 (if (string? s) (Charset/forName s) s)))
A `cond` might be better here. e.g.

```clojure
(defn- ^Charset to-charset [s]
  (cond (nil? s) utf-8 (string? s) (Charset/forName s) :else s))

2023-01-27 17:00 UTC, bsless commented on src/ring/util/codec.clj
> +  (if (nil? s) utf-8 (if (string? s) (Charset/forName s) s)))
I don't mind if you find it more idiomatic, but one thing to consider is the final else case adds two more branches and compiles slightly nicer to bytecode

2023-01-27 17:05 UTC, weavejester commented on src/ring/util/codec.clj
> +  (if (nil? s) utf-8 (if (string? s) (Charset/forName s) s)))
It does feel more idiomatic... but in this case avoiding the extra branch is probably a good idea for performance. So let's keep the two `if`s, but change the first line to `(defn- ^Charset to-charset [s]` to be more consistent with other functions.

2023-01-27 19:50 UTC, bsless commented on src/ring/util/codec.clj
> +(def ^Charset utf-8 (Charset/forName "UTF-8"))
Done

2023-01-27 19:50 UTC, bsless commented on src/ring/util/codec.clj
> +  (if (nil? s) utf-8 (if (string? s) (Charset/forName s) s)))
Done

2023-01-27 19:54 UTC, bsless commented
@weavejester Done proposed changes, added one implicit test of `to-charset`'s behavior by providing different types of arguments in `test-url-encode`.
I didn't change the behavior of `percent-decode`. It already accepted encoding, but I pulled it out of the closure to avoid repeated lookups for each match.

2023-01-30 16:55 UTC, weavejester commented on src/ring/util/codec.clj
> +(defn- to-charset ^Charset [s]
Please swap `to-charset` and `^Charset`. I believe both are valid, but `defn ^Hint name` is used elsewhere in the namespace, and it's more consistent to stick with one format.

2023-01-30 18:04 UTC, bsless commented on src/ring/util/codec.clj
> +(defn- to-charset ^Charset [s]
Done
I remember now why I'm used to hinting the arg vector - the type hints for primitive return types don't work when you hint the var, so I'm just used to it by now

2023-02-01 16:41 UTC, weavejester commented
Thanks for the update. I merged another PR that I didn't expect to conflict with this one, but it did so I'm afraid that you'll have to rebase off master. Sorry about that!

Could you also change the commit message to:

```
Replace charset String type with Charset type

By providing the default encoding as Charset, repeated lookups can be
avoided in hot paths.

Fixes #40.
```

2023-02-01 18:05 UTC, bsless commented
Done :tada:

2023-02-02 05:10 UTC, merged

2025-06-02 17:12 UTC, imrekoszo commented
Just found after a good bit of debugging (after a seemingly innocent minor version bump) that this change breaks Java 8 (and I believe 9) compatibility by depending on overloads of `URLEncoder/encode` and `URLDecoder/decode` that were only added in Java 10 I believe.

Just noting it here in case anyone else comes across it.